# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(722, 640)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(300, 50, 401, 551))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 399, 549))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.btn_open_proj = QtWidgets.QPushButton(Dialog)
        self.btn_open_proj.setGeometry(QtCore.QRect(10, 10, 91, 41))
        self.btn_open_proj.setAutoDefault(False)
        self.btn_open_proj.setDefault(False)
        self.btn_open_proj.setObjectName("btn_open_proj")
        self.btn_init = QtWidgets.QPushButton(Dialog)
        self.btn_init.setGeometry(QtCore.QRect(100, 10, 121, 41))
        self.btn_init.setAutoDefault(False)
        self.btn_init.setObjectName("btn_init")
        self.btn_import_zip = QtWidgets.QPushButton(Dialog)
        self.btn_import_zip.setGeometry(QtCore.QRect(220, 10, 121, 41))
        self.btn_import_zip.setAutoDefault(False)
        self.btn_import_zip.setObjectName("btn_import_zip")
        self.treeView = QtWidgets.QTreeView(Dialog)
        self.treeView.setGeometry(QtCore.QRect(10, 50, 281, 551))
        self.treeView.setObjectName("treeView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.btn_open_proj.setText(_translate("Dialog", "打开"))
        self.btn_init.setText(_translate("Dialog", "创建locally.json"))
        self.btn_import_zip.setText(_translate("Dialog", "zip校验"))
